import Logo from "../assets/logo.png"
import Cpp from "../assets/dsaCpp.jpg"
import Java from "../assets/dsaJava.jpg"
import Python from "../assets/dsaPy.jpg"
import JavaScript from "../assets/dsaJs.jpg"
import DsaBasics from "../assets/dsaBasic.png"
import DsaAdv from "../assets/dsaAlgo.jpg"
import WebDev from "../assets/WebDev.png"
import Dsa from "../assets/Dsa.png"
import ProfileIcon from "../assets/ProfileIcon.avif"
import serverIssue from "../assets/server.svg"
import leetCode from "../assets/leetCode.svg"
import codingNinjas from "../assets/CODING.jpg"
import striver_79 from "../assets/striver_79.jpg"
export {Logo,Cpp,Java,Python,JavaScript,DsaBasics,DsaAdv,WebDev,Dsa,ProfileIcon,serverIssue,leetCode,codingNinjas,striver_79};